# Generated by Django 4.2.4 on 2023-09-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(upload_to=None, verbose_name='Profil Fotoğrafı'),
        ),
    ]
